id: 94d144dc28334e5e94c60a44b96ad9da
initial_creation_type: ocr
source_metadata:
  volumes:
    219dd5a8161548d8b5339b01117567bd:
      base_file: v034.txt
      image_group_id: I1PD95879
      title: ''
      total_pages: 1734
      volume_number: 34
